gangpaden = [
    "AGF",
    "Panklaar",
    "Slagerij",
    "VVP",
    "Internationaal",
    "Zuivel",
    "Soepen",
    "Groentenconserven",
    "Fruitconserven",
    "Bakken",
    "Zuren & Sausen",
    "Mediteraanse Specialiteiten",
    "Oliën",
    "Wijn",
    "Chips",
    "Bier",
    "Fris",
    "Pakfris & Sappen",
    "Snoep & Chocola",
    "Dierenvoeding",
    "Schoonmaak",
    "Houdbare Zuivel",
    "Papier",
    "Baby Artikelen",
    "Cosmetica",
    "HEMA",
    "Koffie Koek",
    "Ontbijtgranen",
    "Diepvries",
    "Dieet",
    "Vleesconserven",
    "Bakkerij",
    "Versplein",
    "Servicebalie"
]